[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["yt-dlp", "ffmpeg"]

[build.nixpacksPlan.phases.install]
cmds = ["npm ci"]

[build.nixpacksPlan.phases.build]
cmds = ["npm run deploy-commands"]

[deploy]
startCommand = "npm start"
